services:
  client:
    container_name: tgc-client
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    env_file: "./frontend/.env.development.local"
    environment:
      - NODE_ENV=development
      - API_URL=http://server:3000
    ports:
      - 5173:5173
    volumes:
      - ./frontend/vite.config.ts:/app/frontend/vite.config.ts
      - ./frontend/codegen.ts:/app/frontend/codegen.ts
      - ./frontend/index.html:/app/frontend/index.html
      - ./frontend/public/:/app/frontend/public/
      - ./frontend/src/:/app/frontend/src/
    depends_on:
      server:
        condition: service_healthy # the `server` should be up and healthy prior to starting the `client`, so the codegen script can be safely run to automatically generate the TypeScript types.

  server:
    container_name: tgc-server
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file: "./backend/.env"
    environment:
      - NODE_ENV=development
      - DB_HOST=db # override DB_HOST in .env (localhost by default when the backend is run without a Docker containter, but use service name when running the backend with Docker to connect to the database container).
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_started
    volumes:
      - ./backend/src/:/app/backend/src/
    # Ensure the `server` is up and healthy by fetching the GraphQL schema before starting the `client`.
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "-X",
          "POST",
          "http://localhost:3000",
          "-H",
          "Content-Type: application/json",
          "-d",
          '{"query": "query {__typename}"}',
        ]
      interval: 5s
      timeout: 90s

  db:
    container_name: tgc-db
    image: postgres
    shm_size: 128mb # shared memory limit
    env_file: "./backend/.env"
    ports:
      - 5432:5432
    volumes:
      # No volume: data is stored in the container! Not sustainable solution!
      # Anonymous volume (fully managed by Docker, will be deleted when manually removing the container, enough for local dev):
      # - /var/lib/postgresql/data
      # Named volume (can only be deleted manually, recommended for production):
      - pgdata:/var/lib/postgresql/data

# Specify docker-compose to create the named volume used to persist the database.
volumes:
  pgdata:
    driver: local
