services:
  client:
    build:
      context: .
      args:
        - BUILD_CONTEXT=frontend
    environment:
      - NODE_ENV=development
    env_file:
      - ./frontend/.env.development.local
    ports:
      - 5173:5173
    volumes:
      - ./frontend/index.html:/app/frontend/index.html
      - ./frontend/src/:/app/frontend/src/
      - ./frontend/public/:/app/frontend/public/
      - ./frontend/vite.config.ts:/app/frontend/vite.config.ts
  server:
    build:
      context: .
      args:
        - BUILD_CONTEXT=backend
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
    volumes:
      - ./backend/src/:/app/backend/src/
      - ./backend/database/:/app/backend/database/
