GET http://localhost:3000/ads

###

GET http://localhost:3000/ads?category=bikes

###

GET http://localhost:3000/ads/61

###

POST http://localhost:3000/ads
Content-Type: application/json

{ 
    "title": "New title",
    "description": "New description",
    "owner": "toto@email.com",
    "price": 20.3,
    "picture": "https://www.automobile-magazine.fr/asset/cms/34973/config/28294/apres-plusieurs-prototypes-la-bollore-bluecar-a-fini-par-devoiler-sa-version-definitive.jpg",
    "location": "New location",
    "category": {
      "id": 15
    }
}

###

DELETE http://localhost:3000/ads/61

### 

PATCH http://localhost:3000/ads/61
Content-Type: application/json

{
    "title": "Partially updated title",
    "description": "Partially updated description",
    "location": "Partially updated location",
    "category": {
      "id": 1
    }
}

###

PUT http://localhost:3000/ads/61
Content-Type: application/json

{
    "title": "Updated item",
    "description": "Updated description",
    "owner": "mynewupdatedemail@mail.com",
    "price": 1,
    "picture": "https://www.updated-url.com",
    "location": "Updated location",
     "category": {
      "id": 15
    }
}