GET http://localhost:3000/categories

###

GET http://localhost:3000/categories/1

###

POST http://localhost:3000/categories
Content-Type: application/json

{ 
    "name": "New category"
}

###

DELETE http://localhost:3000/categories/16

### 
PATCH http://localhost:3000/categories/16
Content-Type: application/json

{
    "name": "Partially updated name"
}

###

PUT http://localhost:3000/categories/16
Content-Type: application/json

{
    "name": "Updated name"
}

