GET http://localhost:3000/tags

###

GET http://localhost:3000/tags?name=second-hand

###

GET http://localhost:3000/tags/16

###

POST http://localhost:3000/tags
Content-Type: application/json

{ 
    "name": "New tag"
}

###

DELETE http://localhost:3000/tags/1

### 
PATCH http://localhost:3000/tags/1
Content-Type: application/json

{
    "name": "Partially updated name"
}

###

PUT http://localhost:3000/tags/1
Content-Type: application/json

{
    "name": "Updated name"
}

